server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5010/pizzeria
    username: w0lin
    password: admin
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect